// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

import (
	time "time"
)

type Message struct {
	ID        string `json:"id"`
	UserID    string
	CreatedAt time.Time `json:"createdAt"`
	Text      string    `json:"text"`
}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
